---
- name: Setup Host with additional hardening, email notifications, incus, VPN, and reverse proxy
  hosts: all
  become: true

  roles:
    #- host_harden
    - postfix_relay
    - incus
    #- wireguard
