---
- name: Add Media logical volume to pve volume group
  hosts: proxmox
  become: true

  tasks:
    - name: Create 120GiB LV for media
      community.general.lvol:
        vg: pve
        lv: media
        size: 120g
        state: present

    - name: Create ext4 filesystem on /dev/pve/media
      ansible.builtin.filesystem:
        fstype: ext4
        dev: /dev/pve/media

    - name: Create mount point directory
      ansible.builtin.file:
        path: /mnt/media
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Add mount to /etc/fstab
      ansible.builtin.mount:
        path: /mnt/media
        src: /dev/pve/media
        fstype: ext4
        opts: defaults
        state: mounted

    - name: Define Proxmox storage "media-storage"
      ansible.builtin.blockinfile:
        path: /etc/pve/storage.cfg
        marker: "# {mark} ANSIBLE MANAGED MEDIA STORAGE"
        block: |
          dir: media-storage
              path /mnt/media
              content none
      notify: reload proxmox storage

  handlers:
    - name: reload proxmox storage
      ansible.builtin.command: pvesm status
