---
- name: Create admin
  hosts: all
  become: yes
  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

  tasks:
    - name: Install sudo
      apt:
        name:
          - sudo
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Create admin user
      user:
        name: admin
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Set up SSH for admin
      authorized_key:
        user: admin
        state: present
        key: "{{ ssh_public_key }}"
